# Generated by Django 4.2.30 on 2026-07-13 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reported_status', models.CharField(choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied')], max_length=10)),
                ('source_weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='parking.parkingslot')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'update_logs',
                'indexes': [models.Index(fields=['slot', '-logged_at'], name='idx_logs_slot_time')],
            },
        ),
    ]
