GEOFENCE_RADIUS_METERS = 15
MAX_SPEED_MS = 55
DRIVER_SOURCE_WEIGHT = 0.40
MARSHAL_SOURCE_WEIGHT = 1.00
RATE_LIMIT_PER_MINUTE = 10
MAP_GRID_CACHE_TTL = 10
LOCATION_CACHE_TTL = 3600
LOG_RETENTION_DAYS = 30
