# Generated by Django 4.2.30 on 2026-07-13 18:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_code', models.CharField(max_length=50, unique=True)),
                ('street_name', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=50)),
                ('parking_type', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('current_status', models.CharField(choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied')], default='FREE', max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parking_slots',
                'indexes': [models.Index(fields=['location'], name='idx_slots_spatial')],
            },
        ),
    ]
