# Generated by Django 4.2.30 on 2026-07-02 16:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('billing_rate_hour', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('boundary_polygon', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'zones',
                'indexes': [models.Index(fields=['boundary_polygon'], name='idx_zones_spatial')],
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_code', models.CharField(max_length=20)),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('current_status', models.CharField(choices=[('FREE', 'Free'), ('OCCUPIED', 'Occupied')], default='FREE', max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.zone')),
            ],
            options={
                'db_table': 'parking_slots',
                'indexes': [models.Index(fields=['coordinate'], name='idx_slots_spatial')],
                'unique_together': {('zone', 'slot_code')},
            },
        ),
    ]
