# Generated by Django 4.2.30 on 2026-07-13 15:03

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        CreateExtension('postgis'),
    ]
